name: Test Angular Projects
on: push

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [ 10.16.3 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Setup for ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Determine npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - name: Restore npm cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

  sonar:
    runs-on: ubuntu-latest
    needs: test
    name: SonarCloud Trigger
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: npm ci --prefer-dist --no-progress --no-suggest --no-scripts
    - name: Build & test
      run: npm run build:ci
    - name: Fix for coverage path
      run: sed -i 's/\/home\/runner\/work\/${{ github.repositorie }}\/${{ github.repositorie }}\//\/github\/workspace\//g' lcov.info
      working-directory: ./coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
